### ISSUE TITLE
Cannot compile, getting main.o errors

### ISSUE THREAD

**Issue by Tarik-M** [vigetlabs/platomformio#13]
Hi,

I am trying to get platomformio to work and the install process is okay, but when i try to compile, there is this error that comes from auto-generated files by platomformio. When compiling the output shows that an error occurred in the main.o file. Here is the output:

.pioenvs\uno\libFrameworkArduino.a(main.o): In function `main':
C:\Users\user\Test/.pioenvs\uno\FrameworkArduino/main.cpp:34: undefined reference to`setup'
C:\Users\user\Test/.pioenvs\uno\FrameworkArduino/main.cpp:44: undefined reference to `loop'
collect2.exe: error: ld returned 1 exit status
scons: **\* [.pioenvs\uno\firmware.elf] Error 1
 [ ERROR ] Took 3.91 seconds 

And the code I am trying to compile:

void setup() {
  Serial.bring(9600);
}
void loop() {
  Serial.println("Hi");
}

I'm on windows 8.1

EDIT: nevermind found the issue. Seems to be a general platformio problem, NOT platomformio.

**Comment by efatsi** [comment]
@SoulStormBrew did you figure out what was wrong?

**Comment by Tarik-M** [comment]
@efatsi Yeah, I was trying to compile some code in Atom for a project that includes RF24 radio modules which needs several libraries. Errors occurred and it was both the code and the file structure that were the problem. For some reason the code needs to be compiled in a specific order where every functions made by the user needs to be before loop and setup which isn't a problem in the Arduino IDE.
Also the compiler gave useless errors for libraries i use where it complained about stuff that shouldn't even be used by the compiler (some RPi specific stuff), so i needed to delete it to be able to compile. I was quite confused about it but realized it probably didn't have anything to do with your package and was a platformio problem all together (after I posted the issue) since the errors occurred both in, and outside of atom (when using command line to compile).

As for the example in the OP, the ino file wasn't in the right folder, my mistake...

**Comment by ivankravets** [comment]
If you use *.cpp extension, you have to  `#include <Arduino.h>` and declare all prototypes which you are going to use. 

If you don't want to do it and like Arduino's behavior, just use `*.ino` extension. Then PlatformIO will do that stuff automatically for you.
