### ISSUE TITLE
"platformio" not recognised

### ISSUE THREAD

**Issue by kitusmark** [vigetlabs/platomformio#21]
Hi! 

I've been tinkering arround with platomformio and I successfully compile and upload my code but only a few times. There's a moment when I do "build" that the console spits out this:

`"platformio" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
[Finished in 0.037s]`

It's in spanish but in English is something like this:

`"platformio" is not recognized as an internal or external command,
program or batch file.`

The thing is I'm able to do `platformio run` on the cmd line and I compile everything.
Am I doing something wrong?

I'm running Atom v1.4.3 and platomformio 0.7.1

**Comment by efatsi** [comment]
If you can run `platformio run` from the command line, then it should just be a matter of setting the `Environment PATH` setting in the platomformio package. Pasting in your command line's full path is the heavy-handed approach but should work.

**Comment by kitusmark** [comment]
I've tried that nothing changes. When this happens I reboot Atom and it works again. 
Thanks anyway
