### ISSUE TITLE
I can't install platomformio!

### ISSUE THREAD

**Issue by AlexandruGoman** [vigetlabs/platomformio#22]
I can't install platomformio....It simply won't install....i click install in the atom app and it doesn't work...help please! Thank you!

**Comment by ivankravets** [comment]
Try this https://atom.io/packages/platformio-ide

**Comment by AlexandruGoman** [comment]
Thank you! Thank you! Thank you! Thank you! You are the best!

**Comment by AlexandruGoman** [comment]
Hey dude i ran into another problem.....i doesn't recognize my librarys....what should i do?

**Comment by ivankravets** [comment]
@AlexandruGoman please post to https://community.platformio.org
