### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by arielpchara** [vigetlabs/platomformio#4]
Error: The PlatformIO and `scons` aren't installed properly. Please use official installation manual: http://docs.platformio.org/en/latest/installation.html

**Comment by efatsi** [comment]
I get this same error if I don't open Atom from within Terminal. If I open it through any other means the PATH is not loaded with it and it can't find necessary dependencies.

**Comment by g-zajac** [comment]
The same error when launched with icon, no error when I launch Atom from terminal. Also during compilation process a message window pops in: The "gcc" command recuires the command line developer tools... and prompt for Xcode installation. Is the installation necessary?

**Comment by efatsi** [comment]
Perhaps. I've always had Xcode so I wouldn't know otherwise.

**Comment by ShaharHD** [comment]
I'm also having the same issue. If atom is opened from terminal - no issue, any other way (Icon, Spotlight, etc.) - the error appears.

Btw - if verbose build is not turned on you won't see the error message as the notification bar at the bottom doesn't register this as an error.

**Comment by efatsi** [comment]
The solution to the problem is to open it from the terminal.

**Comment by efatsi** [comment]
Update: a new minor version has been pushed (0.5.0) that allows you to update your PATH, which can be used to resolve this issue no matter which way you open Atom.

PR: https://github.com/vigetlabs/platomformio/pull/5
Check the Readme Settings section for information on updating PATH: https://github.com/vigetlabs/platomformio#settings

**Comment by ShaharHD** [comment]
Solves the issue but creates a different side affect issue.
If opening Atom from any location other than the command line, it doesn't pickup on the path (which is easy to fix using the settings).

Is there an easy way to make that once the package is installed/upgraded, if no path is set - to pull the current path settings from the console? (like running echo $PATH once and capturing the output?)
