### ISSUE TITLE
Cross-platform keymap

### ISSUE THREAD

**Issue by ivankravets** [vigetlabs/platomformio#6]
How is difficult to implement cross-platform keymap? Or change hot-keys to `Ctrl+Shift+*`? It will allow to use Atom IDE on Win/Linux OS.

**Comment by efatsi** [comment]
I only have access to OSX, so wouldn't be able to test any solutions personally. Any user is able to define their own custom keybindings in Atom.

**Comment by ivankravets** [comment]
> Any user is able to define their own custom keybindings in Atom.

Cool!

P.S: Does "Command palette" `Cmd+P` work for you? I can't find any related `platomformio` commands :(

**Comment by efatsi** [comment]
It does indeed:
![image](http://i.imgur.com/2msXfcU.png)

**Comment by ivankravets** [comment]
Which is version of Atom?

**Comment by lukehoggett** [comment]
If it helps I have found, on Ubuntu, Atom 1.09 that the suggested keymaps e.g. `shift-cmd-B` work using `shift-super-B`

**Comment by efatsi** [comment]
thanks for the suggestion, I'll swap them out with `super`.
