### ISSUE TITLE
I think this is not a core atom package anymore

### ISSUE THREAD

**Issue by steam228** [vigetlabs/platomformio#7]
Sorry, very new on this:

I keep receiving this message " Cannot find module 'atom-space-pen-views'" even after installing this same package it asks for.

Thanks in advance,

André

**Comment by efatsi** [comment]
Is this in normal use of the package, or are you trying to work on it locally?

**Comment by steam228** [comment]
I think locally. Followed the instructions and keep receiving that message.

**Comment by efatsi** [comment]
Can you paste a screenshot of the error you're seeing?

**Comment by steam228** [comment]
Just re-installing everything for the 3rd time on a very very slow connection...i will in a minute

**Comment by steam228** [comment]
ok, just to leave a final note:
After reinstalling the error became different and more clear:
platformio path location, solved and working.

About the previous error, can't figure why it was happening.

Thank you anyway,

Best

**Comment by ivankravets** [comment]
@steam228 have you resolved this issue?
